### ISSUE TITLE
Crash on windows when using dlopen("libchemfiles.dll")

### ISSUE THREAD

**Issue by Luthaf** [JuliaBinaryWrappers/Chemfiles_jll.jl#1]
Running `using Chemfiles_jll` on 64-bit Windows (I did not try with 32-bit) crashes the julia process with no stack trace.

I tracked this down to a crash when running `Libdl.dlopen("bin/libchemfiles.dll")`. The same crash happens if I try to open the DLL with Python (again, crash with no message and no stack trace)

```
import ctypes
ctypes.cdll.LoadLibrary("bin/chemfiles.dll")
```

---
```
$ dumpbin /dependents libchemfiles.dll
Microsoft (R) COFF/PE Dumper Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.


Dump of file libchemfiles.dll

File Type: DLL

  Image has the following dependencies:

    libgcc_s_seh-1.dll
    libstdc++-6.dll
    ADVAPI32.dll
    KERNEL32.dll
    msvcrt.dll
    libwinpthread-1.dll
    WS2_32.dll
```

Most of the dependencies seems to be resolved on my VM, except for a single `???` dependency that is not seen by `dumpbin.exe`

```
 ldd libchemfiles.dll
        ntdll.dll => /c/Windows/SYSTEM32/ntdll.dll (0x7fff3e1c0000)
        KERNEL32.DLL => /c/Windows/System32/KERNEL32.DLL (0x7fff3d640000)
        KERNELBASE.dll => /c/Windows/System32/KERNELBASE.dll (0x7fff3a430000)
        apphelp.dll => /c/Windows/SYSTEM32/apphelp.dll (0x7fff38540000)
        USER32.dll => /c/Windows/System32/USER32.dll (0x7fff3de00000)
        win32u.dll => /c/Windows/System32/win32u.dll (0x7fff3a970000)
        GDI32.dll => /c/Windows/System32/GDI32.dll (0x7fff3d480000)
        gdi32full.dll => /c/Windows/System32/gdi32full.dll (0x7fff3a780000)
        msvcp_win.dll => /c/Windows/System32/msvcp_win.dll (0x7fff3ab70000)
        ucrtbase.dll => /c/Windows/System32/ucrtbase.dll (0x7fff3a2d0000)
        IMM32.DLL => /c/Windows/System32/IMM32.DLL (0x7fff3d0d0000)
        ADVAPI32.dll => /c/Windows/System32/ADVAPI32.dll (0x7fff3dd50000)
        libstdc++-6.dll => /mingw64/bin/libstdc++-6.dll (0x6fc40000)
        libgcc_s_seh-1.dll => /mingw64/bin/libgcc_s_seh-1.dll (0x61440000)
        msvcrt.dll => /c/Windows/System32/msvcrt.dll (0x7fff3d100000)
        ??? => ??? (0x620000)
        libwinpthread-1.dll => /mingw64/bin/libwinpthread-1.dll (0x64940000)
        sechost.dll => /c/Windows/System32/sechost.dll (0x7fff3dc90000)
        RPCRT4.dll => /c/Windows/System32/RPCRT4.dll (0x7fff3db00000)
        WS2_32.dll => /c/Windows/System32/WS2_32.dll (0x7fff3d4b0000)
```
---

@staticfloat @giordano, any idea on what is going wrong here?

**Comment by giordano** [comment]
Uhm, this is a C++ project, I wonder if we need to use `expand_cxxstring_abis`

**Comment by Luthaf** [comment]
Maybe, but the interface used by julia is a pure C interface, C++ strings are only used internally.

**Comment by giordano** [comment]
> Maybe, but the interface used by julia is a pure C interface, C++ strings are only used internally.

Ok, makes sense probably.

> I tracked this down to a crash when running Libdl.dlopen("bin/libchemfiles.dll").

Could you please point me to the line in the source code where this happen?

**Comment by Luthaf** [comment]
https://github.com/JuliaBinaryWrappers/Chemfiles_jll.jl/blob/3bb5fe5687d6ef41cb99af77ca9acb120ea73ce8/src/wrappers/x86_64-w64-mingw32.jl#L37

**Comment by Luthaf** [comment]
Also, the version built on conda-forge (https://github.com/chemfiles/chemfiles-lib-feedstock / https://anaconda.org/conda-forge/chemfiles-lib) loads fine with both Python and Julia.

It is natively built on Windows using MSVC instead of cross-compiled with GCC.

**Comment by giordano** [comment]
Oh, it is here, I thought there was a line in `Chemfiles.jl` trying to dlopen the library again.  Ok, this is weird.

**Comment by Luthaf** [comment]
Yeah, just `using Chemfiles_jll` fails =/

**Comment by giordano** [comment]
Also `ObjectFile.jl` shows the same dependencies as those found by dumpbin:
```
julia> using ObjectFile

julia> readmeta("tmp/mozilla_mose0/Chemfiles.v0.9.2.x86_64-w64-mingw32/bin/libchemfiles.dll") do oh
           find_libraries(oh)
       end
Dict{String,String} with 7 entries:
  "libwinpthread-1.dll" => "libwinpthread-1.dll"
  "libgcc_s_seh-1.dll"  => "libgcc_s_seh-1.dll"
  "libstdc++-6.dll"     => "libstdc++-6.dll"
  "msvcrt.dll"          => "msvcrt.dll"
  "WS2_32.dll"          => "WS2_32.dll"
  "KERNEL32.dll"        => "KERNEL32.dll"
  "ADVAPI32.dll"        => "ADVAPI32.dll"
```
I have no idea what's the `???` shown by `ldd` (I didn't even know there was an `ldd` for Windows!).

**Comment by Luthaf** [comment]
> I didn't even know there was an ldd for Windows!

I am using the one that comes with mingw I think. But it might not be working very well.

**Comment by giordano** [comment]
For the record, I'm doing some tests in a fork of this repo.  32-bit Windows works fine, only the 64-bit libraries is somewhat borked.

**Comment by giordano** [comment]
@Luthaf would it be possible for you to run the tests of your package on 64-bit Windows using [this dll](https://github.com/giordano/Chemfiles_jll.jl/blob/windows-testing/test/libchemfiles.dll).  This has been built with C++11 string ABI.  I was at least able to successfully `dlopen` it on AppVeyor and Travis.

**Comment by giordano** [comment]
Closing this in favour of https://github.com/JuliaPackaging/BinaryBuilder.jl/issues/603
